# Generated by Django 3.0.6 on 2020-06-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('KR', 'Korean'), ('HI', 'Hindi'), ('TM', 'Tamil'), ('MD', 'Mandarin')], max_length=2)),
                ('user_rating', models.FloatField()),
                ('rating_label', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.ManyToManyField(related_name='movies_in_genre', to='app_movie.Genre')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies_in_rating', to='app_movie.Rating')),
            ],
        ),
    ]
