# Generated by Django 3.0.6 on 2020-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('KR', 'Korean'), ('HI', 'Hindi'), ('TM', 'Tamil'), ('MD', 'Mandarin')], db_index=True, max_length=2),
        ),
    ]
