# Generated by Django 3.0.6 on 2020-06-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0002_auto_20200602_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies_in_genre', to='app_movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('KR', 'Korean'), ('HI', 'Hindi'), ('TM', 'Tamil'), ('MD', 'Mandarin'), ('-', 'N/A')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies_in_rating', to='app_movie.Rating'),
        ),
    ]
