# Generated by Django 3.0.6 on 2020-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0003_auto_20200602_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies_in_genre', to='app_movie.Genre'),
        ),
    ]
